name: Daily Performance Check

on:
  schedule:
    # Run once daily at 9 AM UTC (2:30 PM IST)
    - cron: '0 9 * * *'
  
  workflow_dispatch:

jobs:
  check-performance:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      
      - name: Generate performance report
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          cd backend
          python scripts/performance_report.py
